import * as THREE from "three";
import { GLTF } from "three-stdlib";

export type GLTFResult = GLTF & {
  nodes: {
    Object_14: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_43: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_55: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_57: THREE.Mesh;
    Object_59: THREE.Mesh;
    Object_61: THREE.Mesh;
    Object_63: THREE.Mesh;
    Object_65: THREE.Mesh;
    Object_67: THREE.Mesh;
    Object_68: THREE.Mesh;
    Object_70: THREE.Mesh;
    Object_79: THREE.Mesh;
    Object_82: THREE.Mesh;
    Object_83: THREE.Mesh;
    Object_85: THREE.Mesh;
    Object_86: THREE.Mesh;
    Object_88: THREE.Mesh;
    Object_90: THREE.Mesh;
    Object_91: THREE.Mesh;
    Object_93: THREE.Mesh;
    Object_95: THREE.Mesh;
    Object_97: THREE.Mesh;
    Object_99: THREE.Mesh;
    Object_101: THREE.Mesh;
    Object_104: THREE.Mesh;
  };
  materials: {
    city_tex: THREE.MeshPhysicalMaterial;
    sidewalk_tile: THREE.MeshStandardMaterial;
    ground_block: THREE.MeshStandardMaterial;
    Default_Material: THREE.MeshStandardMaterial;
    lambert2: THREE.MeshStandardMaterial;
    police_station_tex: THREE.MeshStandardMaterial;
    Logo_1: THREE.MeshStandardMaterial;
    Logo: THREE.MeshPhysicalMaterial;
    MI_city_ufo_Minimap: THREE.MeshStandardMaterial;
  };
};

export type ActionName = "ufo_01";
