import * as THREE from "three";
import { GLTF } from "three-stdlib";

export type GLTFResult = GLTF & {
	nodes: {
		Object_5: THREE.Mesh;
		Object_7: THREE.Mesh;
		Object_9: THREE.Mesh;
		Object_11: THREE.Mesh;
		Object_13: THREE.Mesh;
		Object_15: THREE.Mesh;
		Object_17: THREE.Mesh;
		Object_19: THREE.Mesh;
		Object_21: THREE.Mesh;
		Object_23: THREE.Mesh;
		Object_25: THREE.Mesh;
		Object_27: THREE.Mesh;
		Object_29: THREE.Mesh;
		Object_31: THREE.Mesh;
		Object_33: THREE.Mesh;
		Object_35: THREE.Mesh;
		Object_37: THREE.Mesh;
		Object_39: THREE.Mesh;
		Object_41: THREE.Mesh;
		Object_43: THREE.Mesh;
		Object_45: THREE.Mesh;
		Object_47: THREE.Mesh;
		Object_49: THREE.Mesh;
		Object_51: THREE.Mesh;
		Object_53: THREE.Mesh;
		Object_55: THREE.Mesh;
		Object_57: THREE.Mesh;
		Object_59: THREE.Mesh;
		Object_61: THREE.Mesh;
		Object_63: THREE.Mesh;
		Object_65: THREE.Mesh;
		Object_67: THREE.Mesh;
		Object_69: THREE.Mesh;
		Object_71: THREE.Mesh;
		Object_73: THREE.Mesh;
		Object_75: THREE.Mesh;
		Object_77: THREE.Mesh;
		Object_79: THREE.Mesh;
		Object_81: THREE.Mesh;
		Object_83: THREE.Mesh;
		Object_85: THREE.Mesh;
		Object_87: THREE.Mesh;
		Object_89: THREE.Mesh;
		Object_91: THREE.Mesh;
		Object_93: THREE.Mesh;
		Object_95: THREE.Mesh;
		Object_97: THREE.Mesh;
		Object_99: THREE.Mesh;
		Object_101: THREE.Mesh;
		Object_103: THREE.Mesh;
		Object_105: THREE.Mesh;
		Object_107: THREE.Mesh;
		Object_109: THREE.Mesh;
	};
	materials: {
		xingguang: THREE.MeshStandardMaterial;
		guangshu: THREE.MeshStandardMaterial;
		guangshushu1: THREE.MeshStandardMaterial;
		yuanhuan: THREE.MeshStandardMaterial;
	};
};

export type ActionName = "Take 001";
export type GLTFActions = Record<ActionName, THREE.AnimationAction>;
